package com.internal.shared.security;

import com.internal.feature.logs_report.models.RequestLog;
import com.internal.feature.logs_report.service.RequestLogService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;
import org.springframework.web.util.ContentCachingRequestWrapper;
import org.springframework.web.util.ContentCachingResponseWrapper;

import com.internal.shared.component.MaskingComponent;
import com.internal.shared.component.ClientIpComponent;

import javax.servlet.FilterChain;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

@Component
@Slf4j
@RequiredArgsConstructor
public class RequestLoggingFilter extends OncePerRequestFilter {

    private final RequestLogService requestLogService;
    private final MaskingComponent maskingComponent;
    private final ClientIpComponent clientIpComponent;

    // Endpoints to exclude from logging (to reduce noise)
    private static final List<String> EXCLUDED_PATHS = Arrays.asList(
            "/swagger-ui",
            "/v3/api-docs",
            "/actuator",
            "/favicon.ico",
            "/webjars",
            "/api/images",
            "/api/v1/customer-images" // Added to fix UTF-8 error on image fetch
    );

    @Override
    protected void doFilterInternal(HttpServletRequest request,
            HttpServletResponse response,
            FilterChain filterChain) throws ServletException, IOException {

        // Skip logging for excluded paths
        String requestUri = request.getRequestURI();
        if (shouldSkipLogging(requestUri)) {
            filterChain.doFilter(request, response);
            return;
        }

        String apiKey = request.getHeader("X-API-KEY");

        long startTime = System.currentTimeMillis();
        ContentCachingRequestWrapper requestWrapper = new ContentCachingRequestWrapper(request);
        ContentCachingResponseWrapper responseWrapper = new ContentCachingResponseWrapper(response);

        Exception caughtException = null;

        try {
            filterChain.doFilter(requestWrapper, responseWrapper);
        } catch (Exception e) {
            caughtException = e;
            throw e;
        } finally {
            long duration = System.currentTimeMillis() - startTime;

            // Build and save request log to database
            RequestLog requestLog = buildRequestLog(requestWrapper, responseWrapper, apiKey, duration, caughtException);
            requestLogService.saveLog(requestLog);

            // Copy response body back
            responseWrapper.copyBodyToResponse();
        }
    }

    /**
     * Build RequestLog object from request data
     * Note: UUID is auto-generated by database, no need to set it manually
     */
    private RequestLog buildRequestLog(ContentCachingRequestWrapper request,
            ContentCachingResponseWrapper response,
            String apiKey,
            long duration,
            Exception exception) {

        String ipAddress = clientIpComponent.extractIpAddress(request);
        String username = extractUsername();
        String endpoint = truncate(request.getRequestURI(), 500);
        String method = request.getMethod();
        Integer statusCode = response.getStatus();
        String userAgent = truncate(request.getHeader("User-Agent"), 255);
        boolean isSuccess = (exception == null && statusCode >= 200 && statusCode < 400);
        String errorMessage = exception != null ? truncate(exception.getMessage(), 500) : null;

        String requestPayload = "";
        try {
            requestPayload = new String(request.getContentAsByteArray(), java.nio.charset.StandardCharsets.UTF_8);
            requestPayload = maskingComponent.maskJsonPayload(truncate(requestPayload, 10000));
        } catch (Exception e) {
            log.warn("Failed to parse request payload: {}", e.getMessage());
        }

        String responsePayload = "";
        String contentType = response.getContentType();
        if (contentType != null && (contentType.startsWith("image/") || contentType.startsWith("application/pdf")
                || contentType.startsWith("application/octet-stream"))) {
            responsePayload = "[Binary Content - " + contentType + "]";
        } else {
            try {
                responsePayload = new String(response.getContentAsByteArray(), java.nio.charset.StandardCharsets.UTF_8);
                responsePayload = maskingComponent.maskJsonPayload(truncate(responsePayload, 10000));
            } catch (Exception e) {
                log.warn("Failed to parse response payload: {}", e.getMessage());
            }
        }

        return RequestLog.builder()
                .requestPayload(requestPayload)
                .responsePayload(responsePayload)
                // id is auto-generated, don't set it
                .ipAddress(ipAddress)
                .username(username)
                .apiKey(apiKey)
                .endpoint(endpoint)
                .method(method)
                .statusCode(statusCode)
                .userAgent(userAgent)
                .durationMs(duration)
                .isSuccess(isSuccess)
                .errorMessage(errorMessage)
                .createdAt(LocalDateTime.now())
                .build();
    }



    /**
     * Extract username from security context
     */
    private String extractUsername() {
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            if (authentication != null && authentication.isAuthenticated()
                    && !"anonymousUser".equals(authentication.getPrincipal())) {
                String username = authentication.getName();
                return truncate(username, 100);
            }
        } catch (Exception ignored) {
        }
        return null;
    }

    /**
     * Check if path should be excluded from logging
     */
    private boolean shouldSkipLogging(String path) {
        return EXCLUDED_PATHS.stream().anyMatch(path::startsWith);
    }

    /**
     * Truncate string to maximum length to keep data small
     */
    private String truncate(String value, int maxLength) {
        if (value == null) {
            return null;
        }
        return value.length() > maxLength ? value.substring(0, maxLength) : value;
    }
}





